---
title: "Dashboard Project Name Here" 
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE, warning=FALSE}

#------------------------------ Load Packages ----------------------------------------
library(flexdashboard)
library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(shiny)
library(DT)

```

```{r data, include=FALSE}

#---------------------------------- Data Import ----------------------------------------
data_import <- read_xlsx("../data/isoqol_data.xlsx")



#---------------------------------- Data Transformations --------------------------------

# Code for any additional transformations goes here


```

# Cohort

## Row {data-height="200"}

### __Overall Accrual__

```{r}
#---- Enrollment counts for all arms

 # Count the number of distinct IDs
overall_n <- n_distinct(data$case)  %>%  cat()                   

```

### Arm 1

```{r, message=FALSE, echo=FALSE}
#---- Arm 1 enrollment  

# filter for Arm 1 cases only
# Count the number of distinct IDs
arm1_n <- data %>% filter(arm == "A: IFL") %>% with(n_distinct(case)) %>% cat()

```

### Arm 2

```{r}
#---- Arm 2 enrollment  

# filter for Arm 2 cases only
# Count the number of distinct IDs
arm2_n <- data %>% filter(arm == "F: FOLFOX") %>% with(n_distinct(case)) %>% cat()

```

### Arm 3
```{r}
#---- Arm 3 enrollment

# filter for Arm 3 cases only
# Count the number of distinct IDs
arm3_n <- data %>% filter(arm == "G: IROX") %>% with(n_distinct(case)) %>% cat()

```

## Row {data-height="800"}

### Enrollment by Sex {data-width="500"}

```{r, echo=FALSE}
ggplot(data, aes(x=sex)) + 
  geom_bar(stat="count")
```

### Enrollment by Age {data-width="500"}

```{r, echo=FALSE}
ggplot(data, aes(x=arm, y=age,fill=arm)) +
  geom_boxplot() + 
  theme_bw() + 
  ylab("Age at Enrollment (yrs)") 
```

# Surveys

## Row

### Survey Completion Table

```{r, echo=FALSE}
#------- Survey Completion  
# Select the columns we want to show in our table
survey_table <- data %>% select(case, arm, tx_start_dt, tx_end_dt, bsl, mo3, mo6)
datatable(survey_table)
```


