---
title: "Dashboard Project Name Here" 
output:
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE, warning=FALSE}

#------------------------------ Load Packages ----------------------------------------
library(flexdashboard)
library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(shiny)
library(DT)

```


```{r data, include=FALSE}

#---------------------------------- Data Import ----------------------------------------
data_import <- read_xlsx("../data/isoqol_data.xlsx")



#---------------------------------- Data Transformations --------------------------------
data <- data_import %>% 
  mutate(tx_start_dt = as.Date(tx_start_dt),  # convert treatment start to date
         tx_end_dt = as.Date(tx_end_dt))      # convert treatment end to date
  
# YOUR CODE HERE


```

Cohort
======================================================================

Row  {data-height="200"}
-----------------------------------------------------------------------  

### __Overall Accrual__

```{r}
#---- Enrollment counts for all arms

 # Count the number of distinct IDs
overall_n <- n_distinct(data$case)  %>%  cat()                   

valueBox(value = overall_n,
         caption = "Overall Accrual", 
         color = "blue")

```

### Arm 1

```{r, message=FALSE, echo=FALSE}
#---- Arm 1 enrollment  

# filter for Arm 1 cases only
# Count the number of distinct IDs
arm1_n <- data %>% filter(arm == "A: IFL") %>% with(n_distinct(case)) %>% cat()

# Create Value box
valueBox(value = arm1_n, 
         caption = "Arm 1", 
         color = "red")
```

### Arm 2

```{r}
#---- Arm 2 enrollment  

# filter for Arm 2 cases only
# Count the number of distinct IDs
arm2_n <- data %>% filter(arm == "F: FOLFOX") %>% with(n_distinct(case)) %>% cat()


# Create Value box
valueBox(value = arm2_n, 
         caption = "Arm 2", 
         color = "red")
```

### Arm 3

```{r}
#---- Arm 3 enrollment

# filter for Arm 3 cases only
# Count the number of distinct IDs
arm3_n <- data %>% filter(arm == "G: IROX") %>% with(n_distinct(case)) %>% cat()

# Create Value box
valueBox(value = arm3_n, 
         caption = "Arm 3", 
         color = "red")

```

Row {data-height="800"}
-----------------------------------------------------------------------  

### Enrollment by Sex {data-width="400"}

```{r, echo=FALSE}
ggplot(data, aes(x=sex)) + 
  geom_bar(stat="count")
```

### Enrollment by Age {data-width="600"}

```{r, echo=FALSE}
ggplot(data, aes(x=arm, y=age,fill=arm)) +
  geom_boxplot() + 
  theme_bw() + 
  ylab("Age at Enrollment (yrs)") 
```

Surveys  
======================================================================

Row  {data-height="200"}
-----------------------------------------------------------------------  

### __Baseline Completion__
```{r}
 # Count the number of distinct IDs
baseline <- data %>% filter(bsl == "Complete")          
baseline_n <- length(unique(baseline$case))

gauge(value = baseline_n,
      min = 0, 
      max = length(unique(data$case)), 
      label = "Baseline Survey",
      gaugeSectors(success = c(0, length(unique(data$case)))))

```

### __Month 3 Completion__
```{r}
#---- Baseline Completion

 # Count the number of distinct IDs
mo3 <- data %>% filter(mo3 == "Complete")               
mo3_n <- length(unique(mo3$case))

gauge(value = mo3_n,
      min = 0, 
      max = length(unique(data$case)), 
      label = "Month 3",
      gaugeSectors(success = c(60, length(unique(data$case))), 
                   warning = c(40, 59), 
                   danger = c(0, 39)))

```

### __Month 6 Completion__
```{r}
#---- Baseline Completion

 # Count the number of distinct IDs
mo6 <- data %>% filter(mo6 == "Complete")  %>% count(case)                
mo6_n <- length(unique(mo6$case))
gauge(value = mo6_n,
      min = 0, 
      max = length(unique(data$case)), 
      label = "Month 6",
      gaugeSectors(success = c(60, length(unique(data$case))), 
                   warning = c(40, 59), 
                   danger = c(0, 39)))

```



Row  {data-height="800"}  
-----------------------------------------------------------------------  

### Survey Completion Table

```{r, echo=FALSE}
#------- Survey Completion  
# Select the columns we want to show in our table
survey_table <- data %>% select(case, arm, tx_start_dt, tx_end_dt, bsl, mo3, mo6)
datatable(survey_table)
```


